version: 2.1

executors:
  hugo:
    docker:
      - image: cariad/hugo
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
    working_directory: /tmp/workspace

jobs:
  build:
    environment:
      # Don't pull LFS objects during checkout because it'll moan about
      # credentials. We'll pull when we're good and ready.
      - GIT_LFS_SKIP_SMUDGE: 1
    executor: hugo
    steps:
      - checkout

      # Okay, *now* pull LFS objects for this repository. This won't include any
      # submodules, so we'll sort them out later.
      - run: git lfs pull

      # Pull submodules. This won't include LFS objects.
      - run: git submodule sync
      - run: git submodule update --init

      # Okay, *now* pull LFS objects for the themes/earth submodule.
      - run: pushd themes/earth && git lfs pull && popd # cspell:disable-line

      # Build the website.
      - run: hugo --minify

      # We need to pass headers.yml through to the build job so we can set S3
      # object headers after uploading.
      - run: cp headers.yml public

      # Save our hard work so we can publish it later.
      - persist_to_workspace:
          root: public
          paths:
            - "*"

  publish_dry_run:
    executor: hugo
    steps:
      - attach_workspace:
          at: /tmp/public
      - run: cd /tmp/public && aws s3 sync --dryrun --delete . s3://$BUCKET # cspell:disable-line

  publish:
    executor: hugo
    steps:
      - attach_workspace:
          at: /tmp/public
      - run: cd /tmp/public && aws s3 sync --delete . s3://$BUCKET
      - run: s3headersetter -config /tmp/public/headers.yml -bucket $BUCKET # cspell:disable-line

workflows:
  deploy:
    jobs:
      - build

      - publish_dry_run:
          requires:
            - build
          filters:
            branches:
              ignore:
                - main

      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - main
